### ISSUE TITLE
prediction of new miRNAs does not work

### ISSUE THREAD

**Issue by JudithR** [bioinfoUGR/sRNAtoolbox#29]
Hi, 

I'm trying to predict new miRNAs in a plant dataset. When I run the container with the latest version of bowtie and RNAfold and RNAcofold installed locally (as they seem to be not present in the container) I get a whole lot of identical error messages. I also tried with the standalone sRNAbench.jar and got the same error:

```
           START WITH PREDICTION OF NOVEL MICRORNAS

             Will perform prediction with plant model


######################################################################

     sRNAbench/out/Ty1-EA1_S4_predict3/chunk_14.txt.t not found or not accessible

######################################################################

     sRNAbench/out/Ty1-EA1_S4_predict3/chunk_20.txt.t not found or not accessible
######################################################################
Exception in thread "Thread-51" java.lang.NullPointerException
        at libs.RNAfold.parseRNAfoldOutput(RNAfold.java:51)
        at libs.RNAfold.run(RNAfold.java:32)
        at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.NullPointerException
        at libs.RNAfold.parseRNAfoldOutput(RNAfold.java:51)
        at libs.RNAfold.run(RNAfold.java:32)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

The logFile.txt reports the following:

```
2023-11-22 10:18:02.759 INFO: Write out the non-redundant file of: sRNAbench/out/Ty1-EA1_S4_predict3/homologhairpin_sense_SA.grouped for orientation: sense
2023-11-22 10:18:02.76 INFO: Write out the non-redundant file of: sRNAbench/out/Ty1-EA1_S4_predict3/homologhairpin_antisense_SA.grouped for orientation: antisense
2023-11-22 23:20:33.367 WARNING:  no secondary structure found for c_80848:89030:89038. Probably to long: 141 nt.
2023-11-22 23:20:33.367 WARNING:  no secondary structure found for c_74270:101593:101603. Probably to long: 76 nt.
2023-11-22 23:20:33.367 WARNING:  no secondary structure found for c_20260:236291:236298. Probably to long: 121 nt.
2023-11-22 23:20:33.367 WARNING:  no secondary structure found for c_3121:54504:54510. Probably to long: 71 nt.
2023-11-22 23:20:33.367 WARNING:  no secondary structure found for c_60849:12827:12834. Probably to long: 211 nt.
2023-11-22 23:20:33.367 WARNING:  no secondary structure found for c_68126:67120:67139. Probably to long: 137 nt.
```
I checked the sequences in the file tmp and they are not too long, and the length reported in the WARNING is not correct, or not the whole sequence is stored in the file (example of the first sequence):
```
grep -A 2 c_3121:54504:54510 sRNAbench/out/Ty1-EA1_S4_predict3/tmp
>c_3121:54504:54510#SL4.0ch04#4931778#4931848#+
AATGGAGGTCGAAATATATGATTTTTACATTGTTCCCATAAATATTGTG
```

Any ideas how to check whether the error is with RNAfold or with sRNAbench? Or how to solve the error?

Regards
Judith

**Comment by kdallen1** [comment]
@JudithR I'm experiencing the same issue, any luck solving it?
